Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using G2_PetProtect.Models.Agenda;
using G2_PetProtect.Models.Pets;
using G2_PetProtect.Models.Servicos;
using G2_PetProtect.Models.Funcionarios;
using G2_PetProtect.Models.Horarios;


namespace G2_PetProtect.Controllers
{
    public class AgendaController : Controller
    {
           AgendaRepositorio agendinha  = new AgendaRepositorio();
        public ActionResult Index()
        {            
            return View(AgendaRepositorio.Get(""));
        }

        public ActionResult Adicionar()
        {

            ViewBag.vPets = new SelectList(PetsRepositorio.Get(), "idPet", "nomePet");
            ViewBag.vServicos = new SelectList(ServicosRepositorio.Get(string.Empty), "idServico", "nomeServico");
            ViewBag.vFuncionarios = new SelectList(FuncionariosRepositorio.Get(string.Empty), "idFuncionario", "nomeFuncionario");
            ViewBag.vHorarios = new SelectList(HorariosRepositorio.Get(), "idHorario", "Horario");
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Agenda pAgenda)
        {
            agendinha.Create(pAgenda);
            return RedirectToAction("Index");
        }

        public ActionResult Deletar(string pID)
        {
            Agenda A = AgendaRepositorio.achar(pID);
            return View(A);
        }

        [HttpPost, ActionName("Deletar")]
        public ActionResult DeleteConfirma(string pID)
        {
            Agenda A = AgendaRepositorio.achar(pID);
            AgendaRepositorio.Deletar(A);
            return RedirectToAction("Index");
        }

        public ActionResult EditarAgenda(String pID)
        {
            ViewBag.vPets = new SelectList(PetsRepositorio.Get(), "idPet", "nomePet");
            ViewBag.vServicos = new SelectList(ServicosRepositorio.Get(string.Empty), "idServico", "nomeServico");
            ViewBag.vFuncionarios = new SelectList(FuncionariosRepositorio.Get(string.Empty), "idFuncionario", "nomeFuncionario");
            ViewBag.vHorarios = new SelectList(HorariosRepositorio.Get(), "idHorario", "horario");
            Agenda A = AgendaRepositorio.achar(pID);
            return View(A);
        }

        [HttpPost]
        public ActionResult EditarAgenda(Agenda A)
        {
            AgendaRepositorio.Editar(A);
            return RedirectToAction("Index");
        }

    }
    }

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using G2_PetProtect.Models.Funcionarios;
using G2_PetProtect.Models.Agenda;

namespace G2_PetProtect.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.vFuncionarios = new SelectList(FuncionariosRepositorio.Get(string.Empty), "idFuncionario", "nomeFuncionario");
            return View();
        }
    [HttpPost]
        public ActionResult Index(Agenda tentativa)
        {
            List<Agenda> busca = AgendaRepositorio.busca(tentativa);
            return RedirectToAction("Buscar", new {objeto = busca});
        }

    public ActionResult Buscar(List<Agenda>Busca)
    {
        return View();
    }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using G2_PetProtect.Models.Pets;

namespace G2_PetProtect.Controllers
{
    public class PetsController : Controller
    {
         Pets pet = new Pets();
        public ActionResult Index()
        {
            List<Pets> Lista = PetsRepositorio.Get("");
          
            return View(Lista);
        }

        public ActionResult AdicionarPet()
        {       
            return View();
        }

        [HttpPost]
        public ActionResult AdicionarPet(Pets ppet)
        {
            if (ModelState.IsValid)
            {
                PetsRepositorio.Create(ppet);
                return RedirectToAction("Index");

            }
            else
            {
                return View();
            }
        }

        public ActionResult EditarPet(String pID)
        {
            Pets A = PetsRepositorio.achar(pID);
            return View(A);
        }
       
       [HttpPost]
        public ActionResult EditarPet(Pets A)
        {
            PetsRepositorio.Editar(A);
            return RedirectToAction("Index");
        }


        public ActionResult Deletar(string pID)
        {
           Pets A= PetsRepositorio.achar(pID);
           return View(A);
        }

        [HttpPost, ActionName("Deletar")]
        public ActionResult DeleteConfirma(string pID)
        {
            Pets A= PetsRepositorio.achar(pID);
            PetsRepositorio.Deletar(A);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using G2_PetProtect.Models.Servicos;

namespace G2_PetProtect.Controllers
{
    public class ServicosController : Controller
    {
        Servicos servico = new Servicos();
        public ActionResult Index()
        {
            List<Servicos> Lista = ServicosRepositorio.Get("");

            return View(Lista);
        }

        public ActionResult AdicionarServico()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdicionarServico(Servicos pServico)
        {
            if (ModelState.IsValid)
            {
                ServicosRepositorio.Create(pServico);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult EditarServico(String pID)
        {
            Servicos A = ServicosRepositorio.achar(pID);
            return View(A);
        }

        [HttpPost]
        public ActionResult EditarServico(Servicos A)
        {
            ServicosRepositorio.Editar(A);
            return RedirectToAction("Index");
        }


        public ActionResult Deletar(string pID)
        {
            Servicos A = ServicosRepositorio.achar(pID);
            return View(A);
        }

        [HttpPost, ActionName("Deletar")]
        public ActionResult DeleteConfirma(string pID)
        {
            Servicos A = ServicosRepositorio.achar(pID);
            ServicosRepositorio.Deletar(A);
            return RedirectToAction("Index");
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Buscar.cshtml
@model G2_PetProtect.Models.Agenda.Agenda

@{
    ViewBag.Title = "Buscar";
}
 <table>  
  @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.data)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.pets.nomeDono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pets.nomePet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.servico.nomeServico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.servico.precoP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.servico.precoM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.servico.precoG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.funcionario.nomeFuncionario)
            </td>
        </tr>
    }

</table>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model G2_PetProtect.Models.Agenda.Agenda
@{
    ViewBag.Title = "Home Page";
}

<div style="background-color:lightpink" class="jumbotron">
    <h1>Pet shop</h1>
</div>
<div>
    
</div>
@using (Html.BeginForm())
{
    <fieldset role="form">
        <div class="form-group">
            <table>
                <tr>

                    <td> @Html.Label("Funcionarios", htmlAttributes: new { @class = "control-label col-md-2" })</td>

                    <td>@Html.DropDownListFor(model => model.funcionario.idFuncionario, ViewBag.vFuncionarios as SelectList, string.Empty)</td>

                    <td>@Html.Label("Data", htmlAttributes: new { @class = "control-label col-md-2" })</td>

                    <td>
                        @Html.EditorFor(model => model.data)
                        @Html.ValidationMessageFor(model => model.data, "", new { @class = "text-danger" })
                    </td>
                   <td> <input class="btn btn-success" type="submit" value="Salvar" /></td>



                </tr>
            </table>

        </div>
    </fieldset>
}

        <!--
        <div class="row">
            <div class="col-md-4">
                    <h2>Pets</h2>
                    <p>
                       Veja os Pets Já cadastrados
                    </p>
                    <p>  <p><a class="btn btn-default" @Html.ActionLink("Clique Aqui", "Index", "Pets")</a></p></p>
            </div>
            <div class="col-md-4">
                <h2>Serviços</h2>
                <p>Veja os serviços que a petshop oferece</p>
                <p><a class="btn btn-default" @Html.ActionLink("Clique Aqui", "Index", "Servicos")</a></p>
            </div>
            <div class="col-md-4">
                <h2>Funcionarios</h2>
                <p>Verifique os Funcionarios da Sua empresa.</p>
                <p><a class="btn btn-default" @Html.ActionLink("Clique Aqui", "Index", "Funcionarios")</a></p>
            </div>
            <center>
            <div style="margin-left:30%;" class="col-md-4">
                <h2>Agenda</h2>
                <p>Veja a Agenda de Serviços</p>
                <p><a class="btn btn-default" @Html.ActionLink("Clique Aqui", "Index", "Agenda")</a></p>
            </div>
                </</center>>
        </div>-->